intro_to_rails/alpha_blog/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"

  get "about", to: "pages#about"
  # get "about" => "pages#about"

  # this is equivalent to the following - resources :articles
  resources :articles, only: [ :show, :index, :new, :create, :edit, :update, :destroy ]

  get "signup", to: "users#new"
  post "users", to: "users#create"
  resources :users, except: [ :new ]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [ :destroy ]
end

intro_to_rails/alpha_blog/app/models/article.rb
=begin

association types for ActiveRecord entities
belongs_to
has_one
has_many
has_many :through
has_one :through
has_and_belongs_to_many

=end

class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  # article = Article.new
  # article.save // returns false and wont save
  # if a validator is present and the
  # title or description are not present
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

intro_to_rails/alpha_blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :load_article, only: [ :show, :edit, :update, :destroy ]
  before_action :require_user, except: [ :index, :show ]
  before_action :require_same_user, only: [ :edit, :update, :destroy ]

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    # debugger
  end

  def new
    # used in the template if there are errors
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted successfully."
    redirect_to articles_path
  end

  private
  def load_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end
end

intro_to_rails/alpha_blog/app/views/articles/_article.html.erb
<div class='container'>
    <% @articles.each do |article| %>
        <div class='row justify-content-md-center'>
            <div class='col-8 mt-4'>
                <div class="shadow-lg card text-center">
                    <div class="card-header">
                        <% if article.user %>
                            by <%= link_to article.user.username, user_path(article.user) %>
                        <% end %>
                        <% if article.categories.any? %>
                            <div class='mt-2'>
                                <%= render article.categories %>
                            </div>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article), class: 'text-success' %></h5>
                        <%= simple_format truncate(article.description, length: 15), class: 'card-text text-start' %>
                        <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
                        <% if logged_in? and (article.user == current_user or current_user.admin?) %>
                            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-info' %>
                            <%= link_to 'Delete', article_path(article), class: 'btn btn-outline-danger', data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"} %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                            Created <%= time_ago_in_words(article.created_at) %> ago |
                            edited <%= time_ago_in_words(article.updated_at) %> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

intro_to_rails/alpha_blog/app/views/articles/_form.html.erb
<div class='container'>
    <%= render 'shared/errors', obj: @article %>

    <div class='row'>
        <%= form_with model: @article, local: true do |f| %>
            <div class="mb-3">
                <%= f.label :title, class: 'form-label' %>
                <%= f.text_field :title , class: 'form-control' %>
            </div>
            <div class="mb-3">
                <%= f.label :description, class: 'form-label' %>
                <%= f.text_area :description, rows: 10, class: 'form-control', style: 'heidght: 150px;' %>
            </div>

            <div class="mb-3">
                <%= f.label :category, class: 'form-label' %>
                <%= f.collection_select(
                     :category_ids, 
                     Category.all, 
                     :id, 
                     :name, 
                     { 
                        prompt: 'Select a category', 
                        multiple: true,
                        size: 5
                    },
                    class: 'custom-select form-control' 
                ) %>
            </div>
            <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

intro_to_rails/alpha_blog/app/views/articles/edit.html.erb
<div class='py-3' id='page-content'>
    <h1 class='text-center mt-4'>Edit Article</h1>

    <h2 class='text-center'>
        <%= link_to 'Return to listing', articles_path, class: 'btn btn-primary' %>
    </h2>

    <%= render 'form' %>
</div>

intro_to_rails/alpha_blog/app/views/articles/index.html.erb
<div id='page-content'>
    <h1 class='text-center mt-4'>Listing all Articles</h1>
    
    <div class="flickr_pagination">
        <div class="page_info">
            <%= page_entries_info @articles %>
        </div>
        <%= will_paginate @articles, :container => false %>
    </div>

    <%= render 'article' %>

    <div class="flickr_pagination my-5">
        <div class="page_info">
            <%= page_entries_info @articles %>
        </div>
        <%= will_paginate @articles, :container => false %>
    </div>
</div>

intro_to_rails/alpha_blog/app/views/articles/new.html.erb
<div id='page-content'>
    <h1 class='text-center mt-4'>Create a New Article</h1>
    
    <h2 class='text-center'>
        <%= link_to 'Return to listing', articles_path, class: 'btn btn-primary' %>
    </h2>

    <%= render 'form' %>
</div>

intro_to_rails/alpha_blog/app/views/articles/show.html.erb
<div class='py-3' id='page-content'>
    <h1 class='text-center'><%= @article.title %></h1>
    <div class='row mb-4 justify-content-md-center'>
        <div class='col-8 mt-4'>
            <div class="shadow-lg card text-center">
                <div class="card-header">
                    <% if @article.user %>
                        by <%= @article.user.username %>
                    <% end %>
                    <% if @article.categories.any? %>
                        <div class='mt-2'>
                            <%= render @article.categories%>
                        </div>
                    <% end %>
                </div>
                <div class="card-body">
                    <%= simple_format @article.description, class: 'card-text text-start' %>
                    <% if logged_in? and @article.user == current_user or current_user.admin? %>
                        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-info' %>
                        <%= link_to 'Delete', article_path(@article), class: 'btn btn-outline-danger', data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"} %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>
                        Created <%= time_ago_in_words(@article.created_at) %> ago |
                        edited <%= time_ago_in_words(@article.updated_at) %> ago
                    </small>
                </div>
            </div>
        </div>
    </div>

    <h2 class='text-center'>
        <%= link_to 'Return to listing', articles_path, class: 'btn btn-primary' %>
    </h2>

</div>