intro_to_rails/alpha_blog/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"

  get "about", to: "pages#about"
  # get "about" => "pages#about"

  # this is equivalent to the following - resources :articles
  resources :articles, only: [ :show, :index, :new, :create, :edit, :update, :destroy ]

  get "signup", to: "users#new"
  post "users", to: "users#create"
  resources :users, except: [ :new ]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [ :destroy ]
end

intro_to_rails/alpha_blog/app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

intro_to_rails/alpha_blog/app/views/pages/home.html.erb
<div class="hero text-white p-5 bg-body-tertiary rounded-3">
  <div class="text-center container-fluid py-5">
    <h1 class="display-5 fw-bold">Alpha Blog</h1>
    <p class="fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-success" %>
  </div>
</div>