university_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "courses#index"

  get "courses/new", to: "courses#new"

  get "about", to: "pages#about"

  resources :students, except: [ :destroy ]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  post "course_enroll", to: "student_courses#create"
end

university_app/app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  has_many :student_courses
  has_many :students, through: :student_courses
end

university_app/app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  has_many :student_courses
  has_many :courses, through: :student_courses
end

university_app/app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

university_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :require_user

  # makes methods available in the views, as well as the controllers
  # so we can remove it from the application_helper.rb
  helper_method :current_user, :logged_in?

  def current_user
    student_id = session[:student_id]
    @current_user ||= Student.find student_id if student_id
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

university_app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
  end

  def new
  end
end

university_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about
  end
end

university_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [ :new, :create ]
  def new
  end

  def create
    student = Student.find_by email: params[:session][:email].downcase
    if student and student.authenticate(params[:session][:password])
      session[:student_id] = student.id
      flash[:notice] = "You have successfully logged in"
      redirect_to student
    else
      flash.now[:alert] = "There was something wrong with your login information"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

university_app/app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    unless current_user.courses.include?(course_to_add)
      StudentCourse.create(student: current_user, course: course_to_add)
      flash[:notice] = "You have successfully enrolled in #{course_to_add.name}"
      redirect_to current_user
    else
      flash[:notice] = "You are already enrolled in this course"
      redirect_to root_path
    end
  end
end

university_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [ :new, :create ]
  before_action :require_same_student, only: [ :edit, :update ]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "Student was created successfully"
      redirect_to students_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash[:notice] = "Student was updated successfully"
      redirect_to @student
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def require_same_student
    if current_user != @student
      flash[:error] = "You can only edit your own profile"
      redirect_to student_path(current_user)
    end
  end
end

university_app/app/views/courses/index.html.erb
<div class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-3xl">
        <!-- Content goes here -->
        <h3 class='text-center my-4 text-4xl'>Course Listing</h3>

        <ul role="list" class="grid grid-cols-2 divide-y divide-gray-200">
            <% Course.all.each do |course| %>
                <li class="rounded-lg bg-white shadow px-4 py-4 flex w-64 flex-col text-center lg:w-auto">
                    <div class="group relative">
                        <div class="mt-6">
                            <h3 class="font-semibold text-sm text-gray-500"><%= course.short_name %>: <%= course.name %></h3>
                            <p class="mt-1 text-gray-900"><%= course.description %></p>
                            <a class='rounded bg-white px-2 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"' href="#">View Course</a>
                            <% if logged_in? and !(current_user.courses.include?(course)) %>
                                <%= link_to "Enroll", course_enroll_path(course_id: course.id), data: { turbo_method: :post }, class: 'rounded bg-white px-2 py-1 text-xs font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50' %>
                            <% end %>
                        </div>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</div>

university_app/app/views/layouts/_flash.html.erb
    <% flash.each do |name, msg| %>
        <div class="ui <%= name %> message">
            <i class="close icon"></i>
            <div class="header">
                <%= msg %>
            </div>
        </div>
    <% end %>

university_app/app/views/layouts/_footer.html.erb
 <footer class="bg-gray-900">
    <div class="mx-auto max-w-7xl overflow-hidden px-6 py-20 sm:py-24 lg:px-8">
    <nav class="-mb-6 flex flex-wrap justify-center gap-x-12 gap-y-3 text-sm/6" aria-label="Footer">
        <a href="#" class="text-gray-400 hover:text-white">Help</a>
        <a href="#" class="text-gray-400 hover:text-white">About</a>
        <a href="#" class="text-gray-400 hover:text-white">Contact Us</a>
    </nav>
    
    <p class="mt-10 text-center text-sm/6 text-gray-400">&copy; 2024 Tech University, Inc. All rights reserved.</p>
    </div>
</footer>

university_app/app/views/layouts/_navigation.html.erb
<nav class="bg-gray-800" data-controller="menu">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
        <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button 
            type="button"
            class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
            aria-controls="mobile-menu"
            aria-expanded="false"
            data-action="click->menu#toggle"
            data-menu-target="button"
        >
            <span class="sr-only">Open main menu</span>
            <!-- Icon when menu is closed -->
            <svg
            class="block h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            aria-hidden="true"
            data-menu-target="iconClosed"
            >
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <!-- Icon when menu is open -->
            <svg
            class="hidden h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            aria-hidden="true"
            data-menu-target="iconOpen"
            >
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
            </svg>
        </button>
        </div>
        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
            <img class="h-8 w-auto" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=500" alt="Tech University">
        </div>
        <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Courses", root_path, class: "rounded-md px-3 py-2 text-sm font-medium #{current_page?(root_path) ? 'bg-gray-900 text-white' : 'text-gray-300 hover:bg-gray-700 hover:text-white'}", aria: { current: current_page?(root_path) ? "page" : nil } %>

            <% if logged_in? %>
                <%= link_to "Students", students_path, class: "rounded-md px-3 py-2 text-sm font-medium #{current_page?(students_path) ? 'bg-gray-900 text-white' : 'text-gray-300 hover:bg-gray-700 hover:text-white'}", aria: { current: current_page?(students_path) ? "page" : nil } %>
            <% end %>

            <% if logged_in? %>
                <%= link_to 'Log out', logout_path, class: 'rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white', data: { turbo_method: :delete } %>
            <% end %>
            </div>
        </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button
            type="button"
            class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
            data-action="click->notification#show"
        >
            <span class="sr-only">View notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
            </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="relative ml-3" data-controller="dropdown">
            <div>
            <button
                type="button"
                class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"
                id="user-menu-button"
                aria-expanded="false"
                aria-haspopup="true"
                data-action="click->dropdown#toggle"
                data-dropdown-target="button"
            >
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
            </div>
            <div
            class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="user-menu-button"
            tabindex="-1"
            data-dropdown-target="menu"
            >
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
            </div>
        </div>
        </div>
    </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state -->
    <div class="hidden sm:hidden" id="mobile-menu" data-menu-target="menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
                        <%= link_to 'Log out', logout_path, class: 'nav-link', data: { turbo_method: :delete } %>

        <a href="#" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">Courses</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Enrollments</a>
        <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
    </div>
    </div>
</nav>

university_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "University App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/flash' %>
    <main class="">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>