saas_project_app/config/routes.rb
Rails.application.routes.draw do
  get "kanban/index"
  get "kanban/update_status"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  devise_for :users, controllers: { registrations: "registrations" }


  resources :teams do
    resources :memberships do
      collection do
        post :invite
      end
    end
    resources :projects

    resources :kanban, only: [ :index ] do
      patch "update_status", on: :collection
    end
  end

  resources :artifacts
  resources :user_projects
end

saas_project_app/app/models/artifact.rb
class Artifact < ApplicationRecord
  attr_accessor :upload
  belongs_to :project

  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name

  validate :uploaded_file_size

  private
  def uploaded_file_size
    if upload
      errors.add(:upload, "File size must be less than 10MB") unless upload.size <= MAX_FILESIZE
    end
  end
end

saas_project_app/app/controllers/artifacts_controller.rb
class ArtifactsController < ApplicationController
  before_action :set_artifact, only: %i[ show edit update destroy ]

  # GET /artifacts or /artifacts.json
  def index
    @artifacts = Artifact.all
  end

  # GET /artifacts/1 or /artifacts/1.json
  def show
  end

  # GET /artifacts/new
  def new
    @artifact = Artifact.new
    @artifact.project_id = params[:project_id]
  end

  # GET /artifacts/1/edit
  def edit
  end

  # POST /artifacts or /artifacts.json
  def create
    @artifact = Artifact.new(artifact_params)
    @artifact.project_id = params[:artifact][:project_id]

    @project = Project.find(params[:artifact][:project_id])
    @artifact.project = @project
    @project.artifacts << @artifact
    @project.save

    respond_to do |format|
      if @artifact.save
        format.html { redirect_to @artifact, notice: "Artifact was successfully created." }
        format.json { render :show, status: :created, location: @artifact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artifacts/1 or /artifacts/1.json
  def update
    respond_to do |format|
      if @artifact.update(artifact_params)
        format.html { redirect_to @artifact, notice: "Artifact was successfully updated." }
        format.json { render :show, status: :ok, location: @artifact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artifacts/1 or /artifacts/1.json
  def destroy
    @artifact.destroy!

    respond_to do |format|
      format.html { redirect_to artifacts_path, status: :see_other, notice: "Artifact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artifact
      @artifact = Artifact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artifact_params
      params.require(:artifact).permit(:name, :key, :upload, :project_id)
    end
end

saas_project_app/app/helpers/artifacts_helper.rb
module ArtifactsHelper
end

saas_project_app/app/views/artifacts/_artifact.html.erb
<li id="<%= dom_id artifact %>" class="flex items-center justify-between py-4 pl-4 pr-5 text-sm/6">
  <div class="flex w-0 flex-1 items-center">
    <div class="ml-4 flex min-w-0 flex-1 gap-2">
      <span class="truncate font-medium">resume_back_end_developer.pdf</span>
    </div>
  </div>
  <div class="flex w-0 flex-1 items-center">
    <svg class="size-5 shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
      <path fill-rule="evenodd" d="M15.621 4.379a3 3 0 0 0-4.242 0l-7 7a3 3 0 0 0 4.241 4.243h.001l.497-.5a.75.75 0 0 1 1.064 1.057l-.498.501-.002.002a4.5 4.5 0 0 1-6.364-6.364l7-7a4.5 4.5 0 0 1 6.368 6.36l-3.455 3.553A2.625 2.625 0 1 1 9.52 9.52l3.45-3.451a.75.75 0 1 1 1.061 1.06l-3.45 3.451a1.125 1.125 0 0 0 1.587 1.595l3.454-3.553a3 3 0 0 0 0-4.242Z" clip-rule="evenodd" />
    </svg>
    <div class="ml-4 flex min-w-0 flex-1 gap-2">
      <span class="truncate font-medium">resume_back_end_developer.pdf</span>
      <span class="shrink-0 text-gray-400">2.4mb</span>
    </div>
  </div>

  <div class="ml-4 shrink-0">
    <%= link_to "Show", artifact, class: "font-medium text-indigo-600 hover:text-indigo-500" %>
  </div>
  <div class="ml-4 shrink-0">
    <a href="#" class="font-medium text-indigo-600 hover:text-indigo-500">Download</a>
  </div>
</li>

saas_project_app/app/views/artifacts/_form.html.erb
<%= form_with(model: @artifact, url: artifacts_path, local: true, class: 'contents') do |form| %>
  <% if artifact.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(artifact.errors.count, "error") %> prohibited this artifact from being saved:</h2>

      <ul>
        <% artifact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :project_id %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :key %>
    <%= form.text_field :key, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :upload %>
    <%= form.file_field :upload, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

saas_project_app/app/views/artifacts/_list.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
</div>
<div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
  <dt class="text-sm/6 font-medium text-gray-900">
    <div>Attachments</div>
    <% if @project %>
      <%= link_to "New Attachment", new_artifact_path(project_id: @project.id), class: "font-medium text-indigo-600 hover:text-indigo-500" %>
    <% end %>
  </dt>
  <% if artifacts %>
    <dd id='artifacts' class="mt-2 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
      <ul role="list" class="divide-y divide-gray-100 rounded-md border border-gray-200">
        <% artifacts.each do |artifact| %>
          <%= render artifact %>
          
        <% end %>
      </ul>
    </dd>
  <% end %>
</div>

saas_project_app/app/views/artifacts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing artifact</h1>

  <%= render "form", artifact: @artifact %>

  <%= link_to "Show this artifact", @artifact, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to artifacts", artifacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

saas_project_app/app/views/artifacts/index.html.erb
 <%= render 'artifacts/list', artifacts: @artifacts %>

saas_project_app/app/views/artifacts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New artifact</h1>

  <%= render "form", artifact: @artifact %>

  <%= link_to "Back to artifacts", artifacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

saas_project_app/app/views/artifacts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @artifact %>

    <%= link_to "Edit this artifact", edit_artifact_path(@artifact), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to artifacts", artifacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this artifact", @artifact, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>